---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testblog
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: testblog
    spec:
      containers:
      - name: testblog
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/example-eks:e46bd8a06ad852bf5e8257e00ec854740029fdf5
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
