apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: f5581f6f0bcbe68322e52a940b936aa2d9bdc6ad
- name: testblog
  newName: testblog
  newTag: new
