apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: 5a1c5be5274cb68545fc85bb13df5fade5c502b7
- name: testblog
  newName: testblog
  newTag: new
