apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: 3e019d0566cd264b65f5960715ff1bef647474cd
- name: testblog
  newName: testblog
  newTag: new
