apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: 7771059528c23659af10121505e80267ef3a2194
- name: testblog
  newName: testblog
  newTag: new
