apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: 3cd32638bb79940ab14490f4e4d202c1ede50048
- name: testblog
  newName: testblog
  newTag: new
