apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: 527c6ec4a3b19227decabddfbbc7a9d6d732d3fa
- name: testblog
  newName: testblog
  newTag: new
