apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: f6ce2d52e1a7d9c8097c36f8eeeb9294e33581e5
- name: testblog
  newName: testblog
  newTag: new
