apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: aff127efc895c7b54db4fe4d8824b04b9c8fadea
- name: testblog
  newName: testblog
  newTag: new
