apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- testblog-deployment.yaml
- testblog-service.yaml

images:
- name: 258092954359.dkr.ecr.ap-northeast-2.amazonaws.com/testblog
  newTag: bd672258402c6cceb2dd076e21f2085f35d51198
- name: testblog
  newName: testblog
  newTag: new
