apiVersion: v1
kind: Service
metadata:
  name: hello-java-spring-boot-frontend
  labels:
    app: testblog
    tier: frontend 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-java-spring-boot
    tier: frontend
