apiVersion: v1
kind: Service
metadata:
  name: hello-java-spring-boot-frontend
  labels:
    app: testblog
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: LoadBalancer
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-java-spring-boot
    tier: frontend
