apiVersion: v1
kind: Service
metadata:
  name: testblog
  labels:
    app: testblog
    tier: frontend 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: testblog
    tier: frontend
