---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: testblog
  annotations:
    
spec:
  selector:
    matchLabels:
      app: testblog
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: testblog
        tier: frontend
    spec:
      containers:
      - name: testblog
        image: public.ecr.aws/e1s6t4d5/testblog:10492dc9c8f502d16b7ef41920f31036c6b90b38
        # update image value with the image URI of the container registry  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80
