# build.yml
on:
  pull_request:
  push:
    branches:
      - s3deploy
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Check Node v            # Node v 확인
        run: node -v

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env: 
          CI: ""
      
      - name: Deploy to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
          SOURCE_DIR: "build"
        uses: reggionick/s3-deploy@v3
        with:
            folder: build
            bucket: $AWS_S3_BUCKET
            bucket-region: $AWS_DEFAULT_REGION
            dist-id: $AWS_S3_BUCKET
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
